version: "3"

services:
    nginx:
        image: nginx:latest
        restart: unless-stopped
        ports:
            - 5000:5000
        volumes:
            - ./nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - userservice
            - statusservice
            - storyservice

    userservice:
        build: ./user
        restart: unless-stopped
        depends_on:
            - userdb

    userdb:
        image: mongo

        ports:
            - 8003:8003

        restart: unless-stopped
        volumes:
            - /mongo:/data/db

    statusservice:
        build: ./status
        restart: unless-stopped
        depends_on:
            - statusdb

    statusdb:
        image: mongo

        ports:
            - 8001:8001

        restart: unless-stopped

    storyservice:
        build: ./story
        restart: unless-stopped
        depends_on:
            - storydb
            - storyobjectdb

    storydb:
        image: mongo

        ports:
            - 8002:8002

        restart: unless-stopped

    storyobjectdb:
        image: minio/minio:latest
        environment:
            - MINIO_ACCESS_KEY=ILdloFV62IoAlMOV
            - MINIO_SECRET_KEY=bKSQ8DzAZO1wsP5Q9kikl8IBHMAXigZz
            
        command: server --address 0.0.0.0:9000 /data
